name: cmake-Ubuntu-gcc_10

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            BUILD_TYPE: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Initialize compiler (GCC)
      run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
          sudo update-alternatives \
            --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
            --slave /usr/bin/g++ g++  /usr/bin/g++-10 \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-10

    - name: cmake create build env - ${{matrix.BUILD_TYPE}}
      run: cmake -E make_directory ${{github.workspace}}/out/build/${{matrix.BUILD_TYPE}}

    - name: cmake cache - ${{matrix.BUILD_TYPE}}
      shell: bash
      working-directory: ${{github.workspace}}/out/build/${{matrix.BUILD_TYPE}}
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}
      env:
        CC:   gcc-10
        CXX:  g++-10

    - name: cmake build - ${{matrix.BUILD_TYPE}}
      working-directory: ${{github.workspace}}/out/build/${{matrix.BUILD_TYPE}}
      shell: bash
      run: cmake --build . --config ${{matrix.BUILD_TYPE}}

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  shell: bash
    #  # Execute tests defined by the CMake configuration.  
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C $BUILD_TYPE
