name: cmake-Ubuntu-clang_latest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
        matrix:
            BUILD_TYPE: [Debug, Release]
            STL_IMPLEMENTATION: [libstdc++, libc++ -lc++abi]

    steps:
    - uses: actions/checkout@v2

    - name: Initialize compiler (Clang, latest)
      run: |
        sudo apt update
        sudo apt install libstdc++-10-dev
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo update-alternatives \
          --install /usr/bin/clang clang /usr/bin/clang-12 100
        sudo update-alternatives \
          --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 100
        sudo apt install libc++1-12 libc++-12-dev libc++abi-12-dev libc++abi1-12

    - name: cmake create build env - ${{matrix.BUILD_TYPE}} - ${{matrix.STL_IMPLEMENTATION}}
      run: |
        cmake -E make_directory ${{github.workspace}}/out/build/${{matrix.BUILD_TYPE}}
        cmake -E make_directory ${{github.workspace}}/out/install/${{matrix.BUILD_TYPE}}
      
    - name: cmake cache - ${{matrix.BUILD_TYPE}} - ${{matrix.STL_IMPLEMENTATION}}
      run: |
        cmake \
            -DCMAKE_CXX_FLAGS="-stdlib=${{matrix.STL_IMPLEMENTATION}}"                              \
            -DGCL_BUILD_TEST:BOOL=TRUE                                                              \
            -DCMAKE_BUILD_TYPE:STRING="${{matrix.BUILD_TYPE}}"                                      \
            -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/out/install/${{matrix.BUILD_TYPE}}    \
            -S ${{github.workspace}}                                                                \
            -B ${{github.workspace}}/out/build/${{matrix.BUILD_TYPE}}
        
      env:
        CC:   clang-12
        CXX:  clang++-12

    - name: cmake build - ${{matrix.BUILD_TYPE}} - ${{matrix.STL_IMPLEMENTATION}}
      run: |
        cmake \
            --build ${{github.workspace}}/out/build/${{matrix.BUILD_TYPE}}  \
            --config ${{matrix.BUILD_TYPE}}

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  shell: bash
    #  # Execute tests defined by the CMake configuration.  
    #  # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
    #  run: ctest -C $BUILD_TYPE
