name: cmake-Windows-ClangCL

on: [push, pull_request]

env:
  SOLUTION_FILE_PATH: .

jobs:
  build:

    runs-on: windows-latest

    strategy:
        matrix:
            BUILD_TYPE: [Debug, Release]
            ARCH: [Win32, x64]
            GENERATOR: ["Visual Studio 16 2019"]

    steps:
    - uses: actions/checkout@v2

    - name: cmake create build env - ${{matrix.ARCH}} ${{matrix.BUILD_TYPE}}
      run: |
        cmake -E make_directory ${{github.workspace}}/out/build/${{matrix.ARCH}}/${{matrix.BUILD_TYPE}}
        cmake -E make_directory ${{github.workspace}}/out/install/${{matrix.ARCH}}/${{matrix.BUILD_TYPE}}

    - name: cmake cache - ${{matrix.ARCH}} ${{matrix.BUILD_TYPE}}
      #working-directory: ${{github.workspace}}/out/build/${{matrix.ARCH}}/${{matrix.BUILD_TYPE}}
      run: |
        cmake `
            -DGCL_BUILD_TEST:BOOL=TRUE                                                              `
            -DCMAKE_BUILD_TYPE:STRING="${{matrix.BUILD_TYPE}}"                                      `
            -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/out/install/${{matrix.ARCH}}/${{matrix.BUILD_TYPE}} `
            -S ${{github.workspace}}                                                                `
            -B ${{github.workspace}}/out/build/${{matrix.ARCH}}/${{matrix.BUILD_TYPE}}              `
            -G "${{matrix.GENERATOR}}"                                                              `
            -A ${{matrix.ARCH}}                                                                     `
            -T ClangCL
        
    - name: cmake build - ${{matrix.ARCH}} ${{matrix.BUILD_TYPE}}
     #working-directory: ${{github.workspace}}/out/build/${{matrix.ARCH}}/${{matrix.BUILD_TYPE}}
      run: |
        cmake `
            --build ${{github.workspace}}/out/build/${{matrix.ARCH}}/${{matrix.BUILD_TYPE}} `
            --config ${{matrix.BUILD_TYPE}} `
            --parallel 10

    #- name: test
    #  run: cd build ; ctest -j 10 -C Debug --output-on-failure
